CREATE TABLE Person (
    PersonID int PRIMARY KEY ,
    PersonName varchar(100) NOT NULL,
    Salary decimal(8,2) NOT NULL,
    JoiningDate datetime NOT NULL,
    City varchar(100) NOT NULL,
    Age int,
    BirthDate datetime NOT NULL
);

create table PersonLog
(PLogID int Primary key IDENTITY(101,1),
PersonID int not null,
PersonName varchar(250) not null,
Operation varchar(50) not null,
UpdateDate DateTime not null)

--===================PART A===============

--1--------------------------
CREATE TRIGGER TR_PERSON1
ON Person
AFTER INSERT,UPDATE,DELETE
AS
BEGIN
	PRINT'RECORD  IS AFFECTED'
END

INSERT INTO Person VALUES(4,'Deep',10000,'1-1-22','RAJKOT',21,'1-1-2000')
INSERT INTO Person VALUES(5,'Meet',10000,'1-1-22','RAJKOT',23,'1-1-2002')
INSERT INTO Person VALUES(6,'Jay',10000,'1-1-22','RAJKOT',23,'1-1-1999')

UPDATE Person
SET Salary=50000
WHERE PersonName='DEEP'

Delete from Person
where PersonName='Deep'


--2------------------------
-- PERSONLOG INSERT
CREATE TRIGGER TR_PERSONLOGG
ON Person
AFTER INSERT
AS
BEGIN
	INSERT INTO PERSONLOG(PERSONID,PERSONNAME,OPERATION,UPDATEDATE)
	SELECT PERSONID,PERSONNAME,'INSERTED',GETDATE() FROM inserted
END

INSERT INTO Person VALUES(7,'XYZ',10000,'1-1-22','RAJKOT',23,'1-1-1999')


SELECT * FROM  PERSONLOG


-- PERSONLOG UPDATE
CREATE TRIGGER TR_PERSONLOGG_UPDATE
ON Person
AFTER UPDATE
AS
BEGIN
	INSERT INTO PERSONLOG(PERSONID,PERSONNAME,OPERATION,UPDATEDATE)
	SELECT PERSONID,PERSONNAME,'UPDATED',GETDATE() FROM inserted
END

UPDATE Person
SET Salary=50000
WHERE PersonName='XYZ'

SELECT * FROM  PERSONLOG

--PERSONLOG DELETE
CREATE TRIGGER TR_PERSONLOG_DELETE
ON PERSON
AFTER DELETE
AS
BEGIN
	INSERT INTO PERSONLOG(PERSONID,PERSONNAME,OPERATION,UPDATEDATE)
	SELECT PERSONID,PERSONNAME,'DELETED',GETDATE() FROM deleted
END

Delete from Person
where PersonName='MEET'

SELECT * FROM  PERSONLOG


---------------------------------PART B------------------------------------------------------
--1. Insetad Of Insert
CREATE TRIGGER TR_PERSONLOG_INST_INSERT
ON PERSON
INSTEAD OF INSERT
AS
BEGIN
	INSERT INTO PERSONLOG(PERSONID,PERSONNAME,OPERATION,UPDATEDATE)
	SELECT PERSONID,PERSONNAME,'INSERTED',GETDATE() FROM inserted
END

INSERT INTO Person VALUES(8,'XYZ',10000,'1-1-22','RAJKOT',23,'1-1-1999')

SELECT * FROM  PERSONLOG

-- Insetad of update
CREATE TRIGGER TR_PERSONLOG_INST_UPDATE
ON PERSON
INSTEAD OF UPDATE
AS
BEGIN
	INSERT INTO PERSONLOG(PERSONID,PERSONNAME,OPERATION,UPDATEDATE)
	SELECT PERSONID,PERSONNAME,'UPDATED',GETDATE() FROM inserted
END

UPDATE Person
SET Salary=50000
WHERE PersonName='JAY'

SELECT * FROM  PERSONLOG

-- Insetad of Delete
CREATE TRIGGER TR_PERSONLOG_INST_DELETE
ON PERSON
INSTEAD OF DELETE
AS
BEGIN
	INSERT INTO PERSONLOG(PERSONID,PERSONNAME,OPERATION,UPDATEDATE)
	SELECT PERSONID,PERSONNAME,'DELETED',GETDATE() FROM deleted
END

Delete from Person
where PersonName='JAY'

SELECT * FROM  PERSONLOG


--2 UPPERCASE 


--=============== PART C =======================
--1
